name: drinkingtimeui version increment

on:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  version:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/drinkingtimeui
    if: |
      github.event.pull_request.merged &&
      contains(github.event.pull_request.labels.*.name, 'packages:drinkingtimeui')
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{secrets.PAT}}
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: git config --global user.name 'Brian Scaturro'
      - run: git config --global user.email 'scaturrob@gmail.com'
      - run: |
         export NEW_VERSION=$(npm version patch --git-tag-version=false)
         git add package.json package-lock.json
         git commit -m "build(drinkingtimeui): ${NEW_VERSION}"
         git push
